name: Ubuntu 18.04 tonlib-java

on: [push,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:      
        submodules: 'recursive'
    - name: Run Cppcheck
      uses: Bedzior/run-cppcheck@master
      with:
        enabled checks: all
        enable inconclusive: true
        generate report: true
    - name: Upload report
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: output
    - name: Configure
      run: | 
        mkdir build
        cd build
        cmake ..
    - name: Build
      run: |
        export JAVA_AWT_LIBRARY=NotNeeded
        export JAVA_JVM_LIBRARY=NotNeeded
        export JAVA_INCLUDE_PATH=${JAVA_HOME}/include
        export JAVA_AWT_INCLUDE_PATH=${JAVA_HOME}/include
        export JAVA_INCLUDE_PATH2=${JAVA_HOME}/include/linux
        
        cd build
        cmake --build . --target tonlib tonlibjson tonlib-cli --config Release        
        cmake --build . --target prepare_cross_compiling --config Release
        
        cd ../example/android/
        mkdir build
        cd build
        cmake -DTON_ONLY_TONLIB=ON ..        
        cmake --build . --target native-lib --config Release
    - name: find & copy binaries
      run: |
        mkdir -p artifacts/tonlib-java        
        cp example/android/src/drinkless/org/ton/TonApi.java artifacts/tonlib-java/
        cp example/android/build/libnative-lib.so artifacts/tonlib-java/
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-binaries
        path: artifacts
